import Head from 'next/head'
import { usePreviewSubscription } from '../lib/sanity'
import { filterDataToSingleItem } from '../lib/functions'
import { getClient } from '../lib/sanity.server'
import { groq } from 'next-sanity'
import { routeQuery } from '../lib/queries/routeQuery'
import { TextBlocks } from '../components/TextBlocks'
import { useRouter } from 'next/router'
import { GetStaticPaths, GetStaticProps, NextPage } from 'next'
import { Hero, Layout, Link, MarcusIcon, Pane } from 'ui'
import NextLink from 'next/link'
import { MainNav } from '../components/Header/MainNav'
import SanityImage from '../components/SanityImage'

export const getStaticPaths: GetStaticPaths = async () => {
  const routesQuery = groq`
    *[ _type == "Route" && defined(slug.current) && defined(page)] {
    "locales": [
      {
        "lang": page->.__i18n_lang,
        "slug": [slug.current]
      },
      ...page->.__i18n_refs[]->{
        "lang": __i18n_lang,
        "slug": [^.slug.current]
      }
    ],
  }`

  const routes = await getClient().fetch(routesQuery)
  const paths = routes?.map((route: any) => (
    route.locales.map((locale: any) => ({
      params: {
        "slug": locale.slug,
        "locale": locale.lang
      }
    }))
  )) || []

  return {
    paths: paths[0],
    fallback: 'blocking',
  }
}
export const getStaticProps: GetStaticProps = async ({ params, locale, preview = false }) => {
  const slug = typeof params?.slug === 'string' ? params.slug : params?.slug?.join('/')
  const query = routeQuery
  const queryParams = { slug: slug, language: locale }
  const page = await getClient(preview).fetch(routeQuery, queryParams)

  // Escape hatch, if our query failed to return data
  if (!page) return { notFound: true }

  // Helper function to reduce all returned documents down to just one
  // const page = filterDataToSingleItem(data, preview)

  return {
    props: {
      // Pass down the "preview mode" boolean to the client-side
      preview,
      // Pass down the initial content, and our query
      data: { page, query, queryParams },
      //messages: (await import(`../messages/${locale}.json`)).default
    },
  }
}

const Page: NextPage = ({ data, preview }: any) => {
  const { locale, defaultLocale } = useRouter()
  const { data: previewData } = usePreviewSubscription(data?.query, {
    params: data?.queryParams ?? {},
    // The hook will return this on first render
    // This is why it's important to fetch *draft* content server-side!
    initialData: data?.page,
    // The passed-down preview context determines whether this function does anything
    enabled: preview,
  })

  // Client-side uses the same query, so we may need to filter it down again
  const page = filterDataToSingleItem(previewData, preview)
  //console.log(JSON.stringify(page, null, 2))

  const { mainNav, siteSettings: { label } } = page

  {/* If LinguisticDocument the content is in the body field */ }
  const slug = page?.route[0]?.locale[0] ?? page?.route[0]?.fallback[0]
  const linguisticDocumentBody = page?.route[0]?.locale[0]?.body ?? page?.route[0]?.fallback[0]?.body

  const aboutImage = slug?.about ?
    <SanityImage
      image={slug.about.image}
      type='fill'
      alt={slug.about.image?.alt ?? ''}
      priority
    /> : null

  const heroImage = slug?.image ? <SanityImage
    image={slug.image}
    type='fill'
    alt={slug.image?.alt ?? ''}
    priority
  /> : null

  // Notice the optional?.chaining conditionals wrapping every piece of content?
  // This is extremely important as you can't ever rely on a single field
  // of data existing when Editors are creating new documents.
  // It'll be completely blank when they start!
  return (
    <>
      <Head>
        <title>{label[locale || '']}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        data={page}
        header={
          <NextLink href={`/`}>
            {label[locale || '']}
          </NextLink>
        }
        icon={
          <a href="https://marcus.uib.no" aria-label='Go to Marcus'>
            <MarcusIcon className='max-sm:w-6 max-sm:h-6 md:w-8 md:h-8' />
          </a>
        }
        nav={<MainNav value={mainNav} />}
      >
        <Pane intent='content'>
          <Hero
            label={slug?.label}
            image={aboutImage ?? heroImage}
            figCaption={
              <figcaption className='flex w-full justify-end mt-1'>
                <TextBlocks value={slug?.about?.description} />
                <div key={slug?.about?._id}>
                  <p className='font-light text-sm'>
                    <i>
                      <Link href={`/id/${slug?.about?._id}`}>
                        {slug?.about?.label[locale ?? ''] || slug?.about?.label[defaultLocale ?? ''] || 'Missing default language label'}
                      </Link>
                    </i>

                    {slug?.about?.hasCurrentOwner?.length && `. ${slug?.about?.hasCurrentOwner[0].label[locale ?? ''] ?? slug?.about.objectMetadata?.hasCurrentOwner[0].label[defaultLocale ?? '']}.`}
                  </p>
                </div>
              </figcaption>
            }
            creators={slug?.creator}
            locale={locale || ''}
          />

          <div className='mt-5 mb-54 grid grid-cols-content'>
            {linguisticDocumentBody && <TextBlocks value={linguisticDocumentBody} />}
          </div>
        </Pane>
      </Layout>
    </>
  )
}

export default Page