import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Button, AppShell } from "ui";

const Placeholder: NextPage = () => {
  return (
    <>
      <Head>
        <title>Never-ending and temporary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell>
        <div className={`bg-[url('https://data.ub.uib.no/files/bs/ubb/ubb-jg/ubb-jg-k/ubb-jg-k-0276/jpg/ubb-jg-k-0276_md.jpg')] bg-center bg-cover bg-no-repeat h-screen`}>
          <div className={`flex flex-col justify-center items-center h-screen p-5`}>
            <div className="p-5 bg-white/70 flex flex-col gap-3">

              <h1 className="text-6xl text-center font-bold font-sans">Never-ending and temporary</h1>

              <p className='text-xl text-center font-light'>
                New exhibition by the University of Bergen Special collections,
                coming in the beginning of 2023.
              </p>
            </div>
          </div>
        </div>

        <footer>
          <Button>
            <a
              href={`${process.env.NEXT_PUBLIC_STUDIO_URL}/studio`}
              target="_blank"
              rel="noreferrer"
            >
              Studio
            </a>
          </Button>
        </footer>

      </AppShell>
    </>
  );
};

export default Placeholder;
