import React from "react";
import type { GetStaticProps, NextPage } from 'next'
import { getClient } from '../lib/sanity.server'
import { mainNav, siteSettings } from '../lib/queries/fragments'
import Head from "next/head";
import { Button, AppShell, NavigationShell, HeaderShell, LocaleSwitch } from "ui";
import { NextRouter, useRouter } from 'next/router';
import Link from 'next/link';
import { ThemeSwitch } from '../components/ThemeSwitch';
import { groq } from 'next-sanity'
import { MainNav } from '../components/Header/MainNav';

const frontpageQuery = groq`
  {
    ${siteSettings},
    ${mainNav}
  }
`

export const getStaticProps: GetStaticProps = async ({ locale, preview = false }) => {
  const data = await getClient(preview).fetch(frontpageQuery, { language: locale })
  //console.log(JSON.stringify(data, null, 2))
  return {
    props: {
      data,
      locale,
      preview,
      //messages: (await import(`../messages/${locale}.json`)).default
    },
  }
}

const Home: NextPage = ({ data, preview }: any) => {
  const { locale, locales, asPath, defaultLocale }: NextRouter = useRouter()
  const { mainNav, siteSettings: { label } } = data

  return (
    <>
      <Head>
        <title>{label[locale || '']}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell>
        <div className='flex gap-5 px-3 pt-3 pb-1 border-b'>
          <HeaderShell>
            {label[locale || '']}
          </HeaderShell>
          <NavigationShell>
            <MainNav value={mainNav} />
          </NavigationShell>

          <div className='grow'>&nbsp;</div>

          <LocaleSwitch
            locales={locales || []}
            locale={locale || ''}
            defaultLocale={defaultLocale || ''}
            asPath={asPath}
            labels={{
              no: 'Norsk',
              en: 'English'
            }}
          />

          <ThemeSwitch />
        </div>


        <div className='flex flex-col justify-center items-center h-screen gap-5'>
          <h1 className="text-6xl ">{label[locale || '']}</h1>

          <p>
            New exhibition by the University of Bergen Special collections,
            coming in the beginning of 2023.
          </p>
        </div>

        <footer>
          <Button>
            <a
              href={`${process.env.NEXT_PUBLIC_STUDIO_URL}/studio`}
              target="_blank"
              rel="noreferrer"
            >
              Studio
            </a>
          </Button>
        </footer>

      </AppShell>
    </>
  );
};

export default Home;
