import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import { Button, AppShell } from "ui";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Never-ending and temporary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell>

        <div
        /*         bgImage="url('https://data.ub.uib.no/files/bs/ubb/ubb-jg/ubb-jg-k/ubb-jg-k-0276/jpg/ubb-jg-k-0276_md.jpg')"
        backgroundSize='cover'
        backgroundPosition='center'
        backgroundRepeat='no-repeat' */
        >
          <div
          /*           as='main'
          minHeight='100vh'
          py={4}
          px={4}
          flex='1'
          display='flex'
          direction='column'
          justifyContent='center'
          alignItems='center' */
          >
            <h1 className="text-6xl ">Never-ending and temporary</h1>

            <p>
              New exhibition by the University of Bergen Special collections,
              coming in the beginning of 2023.
            </p>
          </div>

          <footer
          /*           as='footer'
          py='2rem'
          flex='1'
          display='flex'
          direction='column'
          justifyContent='center'
          alignItems='center' */
          >
            <Button>
              <a
                href={`${process.env.NEXT_PUBLIC_STUDIO_URL}/studio`}
                target="_blank"
                rel="noreferrer"
              >
                Studio
              </a>
            </Button>
          </footer>
        </div>
      </AppShell>
    </>
  );
};

export default Home;
