import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Never-ending and temporary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Never-ending and temporary
        </h1>

        <p className={styles.description}>
          New exhibition by the University of Bergen Special collections, coming in the beginning of 2023.
        </p>

      </main>

      <footer className={styles.footer}>
        <p>
          Under development by the University of Bergen Library.
          <br />
          <a href={`${process.env.NEXT_PUBLIC_STUDIO_URL}/studio`} target='_blank' rel='noreferrer'>Studio</a>
        </p>
      </footer>
    </div>
  )
}

export default Home
