'use client';
import '../styles/globals.css'
import { ThemeProvider } from 'next-themes';
import { HeaderShell } from 'ui';
import Link from 'next/link';
import { ThemeSwitch } from './ThemeSwitch';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" dir="ltr">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ThemeProvider attribute="class">
          <div className='w-full flex gap-5 px-3 pt-3 pb-2 border-b items-center fixed'>
            <HeaderShell>
              <Link href="/">
                University of Bergen Library API
              </Link>
            </HeaderShell>

            <div className='grow'>&nbsp;</div>
            <Link href={`/spec`}>
              OpenAPI Spec
            </Link>
            <ThemeSwitch />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
